# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # filters:
        #   - name: label
        #     values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__source__']
        regex: '(WARNING|ERROR).*'
        target_label: 'severity'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    # kubernetes_sd_configs:
    #   - scrape_interval: 15s
    #     role: endpoints
    #     relabel_configs:
    #       - source_labels: ['__meta_kubernetes_pod_name']
    #         target_label: 'hostname'
    #         action: replace